### ISSUE TITLE
Many MFIter loops need OMP decorations.

### ISSUE THREAD

**Issue by atmyers** [AMReX-Codes/ExaEpi#19]
@debog I added OpenMP parallelization to the MFIter loops in `AgentContainer.cpp` - could you try to look at the OpenMP scaling again when you get a chance?

**Comment by atmyers** [comment]
@debog would you mind trying this out again with the current `development` code? When I try it, I get decent scaling with number of threads and no race condition.

**Comment by debog** [comment]
> @debog would you mind trying this out again with the current `development` code? When I try it, I get decent scaling with number of threads and no race condition.

@atmyers Sure, I'll try it out in the later this week.

**Comment by debog** [comment]
@atmyers I got seg faults on LLNL Quartz when running with multiple threads. They were "fleeting" with 2 threads but happened consistently with 4 and 8 threads. I moved the bin construction outside the OMP loop (see pull request #25). It is a one-time operation (first time the code flows through interactAgentHomeWork()), so this should be okay? It fixed the seg faults that I was seeing.

**Comment by atmyers** [comment]
Ah yes, the issue that the `[]` operator of `std::map` is not thread safe if it has to create the entry because it's not there. Creating all the map entries first in serial is the right move.

**Comment by debog** [comment]
So the OMP-enabled loop that creates bins in AgentContainer::interactAgents() is fine, right? It doesn't use the map, it just creates bins locally for each MultiFab.

**Comment by atmyers** [comment]
Yes, that part should be fine.
